[tool.poetry]
name = "lacrei-medical-api"
version = "0.1.0"
description = "API RESTful para gerenciamento de consultas médicas."
authors = ["Gabriel Pinto <gabriel.a.m.pinto@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.1.1"
djangorestframework = "^3.18.1"
psycopg = {extras = ["binary"], version = "^3.3.5"}
python-decouple = "^3.8"
djangorestframework-simplejwt = "^5.5.1"
gunicorn = "^26.2.0"
drf-spectacular = "^0.30.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.16.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["RUF012"]
"appointments/serializers.py" = ["RUF012"]